### ISSUE TITLE
Use unique internal identifiers to be able to co-install with other Zowe extension

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-uss-extension-for-zowe#3]
There are conflicts in name spaces for sessions and views with the MVS Zowe extension so the cannot be co-installed at the moment.

![image](https://user-images.githubusercontent.com/4391934/54628967-d216ae00-4a33-11e9-88a1-764f73f1d18f.png)

**Comment by Colin-Stone** [comment]
This has been done in preparation to merging the VSCode extensions.
